###
POST http://localhost:4000/api/users HTTP/1.1
content-Type: application/json

{
    "name": "Nascsor",
    "surname": "astudillo",
    "birthDate": "2000-03-28",
    "DNI": 42475122,
    "age": 22,
    "nationality": "peruano",
    "email": "test@test.com",
    "password": "12345",
}


### 
GET http://localhost:4000/api/users HTTP/1.1

### 
GET http://localhost:4000/api/users/6335c045a391dbfe599f2136 HTTP/1.1

### 
PUT http://localhost:4000/api/users/633b2057e8932d7d5919e945 HTTP/1.1
content-Type: application/json

{
    "name": "Coca-Cola",
    "price": 20,
    "stock": 250,
    "description": "Coca-Cola que se re toma"
}

### 
DELETE http://localhost:4000/api/users/6384fce7ea6641e9d0460086 HTTP/1.1

